version: '3.8'

services:
  app:
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: ${USER}
        uid: ${UID}
    image: kickoff-php
    container_name: kickoff-php-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes: 
      - ./:/var/www
      - ./devops/php:/usr/local/etc/php/conf.d
    networks:
      - kickoff-php
  
  nginx:
    image: nginx:1.17-alpine
    container_name: kickoff-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./devops/nginx:/etc/nginx/conf.d
    networks:
      - kickoff-php

networks:
  kickoff-php:
    driver: bridge